name: build&release
on:
  push:
    tags:
      - "*"
jobs:
  build:
    name: build and release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Parch build Action
        uses: parchlinux/build-action@main
        with:
          gh_apikey: ${{ secrets.GITHUB_TOKEN }}
          release_tag_name: ${{ github.ref_name }}
          repo_name: ${{ github.event.repository.name }}
